# Generated by Django 6.0.2 on 2026-07-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Grains', 'Grains'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits')], max_length=20)),
                ('seller', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
