# Generated by Django 6.0.2 on 2026-07-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('aadhaar', models.CharField(blank=True, max_length=12)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('farm_size', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('farming_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('irrigation', models.CharField(blank=True, choices=[('Rainfed', 'Rainfed'), ('Canal', 'Canal'), ('Drip', 'Drip'), ('Sprinkler', 'Sprinkler'), ('Borewell', 'Borewell')], max_length=20)),
                ('crop', models.CharField(max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
